#!/usr/bin/env bash

usage() {
  echo "-----------------------------"
  echo "Usage:      : $(basename "$0")"
  echo "Description : empty clipboard"
  echo "-----------------------------"
  exit 1
}

if [[ "$1" == "-h" ]]; then
  usage
fi

echo -n | pbcopy
