#!/usr/bin/env bash

usage() {
  echo "----------------------------"
  echo "Usage       : $(basename "$0")"
  echo "Description : launch firefox"
  echo "----------------------------"
  exit 1
}

if [ "$1" == "-h" ] || [ ! -z "$1" ]; then
  usage
fi

open ~/zutlz/ff/Firefox.app

exit 0
