#!/usr/bin/env bash

usage() {
  echo "----------------------------"
  echo "Usage       : $(basename "$0")"
  echo "Description : git branch -a"
  echo "----------------------------"
  exit 1
}

if [ "$1" == "-h" ] || [ ! -z "$1" ]; then
  usage
fi

git branch -a

exit 0
