#!/usr/bin/env bash

usage() {
  echo "----------------------------------"
  echo "Usage       : $(basename "$0") branchname args"
  echo "Description : git branch args"
  echo "----------------------------------"
}

if [[ "$1" == "-h" ]]; then
  usage
  exit 1
fi

git branch "$@"
exit 0
