#!/usr/bin/env bash

usage() {
  echo "----------------------------------"
  echo "Usage       : $(basename "$0") [-b] branchName"
  echo "Description : git checkout [make] branch"
  echo "----------------------------------"
}

if [[ "$1" == "-h" ]]; then
  usage
  exit 1
fi

if [[ -z "$1" ]]; then
  usage
  exit 1
fi

git checkout "$@"
exit 0
