#!/usr/bin/env bash

usage() {
  echo "----------------------------------"
  echo "Usage       : $(basename "$0")"
  echo "Description : git checkout main"
  echo "----------------------------------"
}

if [[ "$1" == "-h" ]]; then
  usage
  exit 1
fi

git checkout main
exit 0
