#!/usr/bin/env bash

usage() {
  echo "----------------------------------"
  echo "Usage       : $(basename "$0") [args]"
  echo "Description : git push to all remotes"
  echo "----------------------------------"
}

if [[ "$1" == "-h" ]]; then
  usage
  exit 1
fi

remotes=$(git remote)

if [[ -z "$remotes" ]]; then
  echo "Error: No git remotes configured."
  exit 1
fi

for remote in $remotes; do
  echo "Pushing to remote: $remote..."
  git push "$remote" "$@"
done

exit 0
