#!/usr/bin/env bash

usage() {
  echo "----------------------------------"
  echo "Usage       : $(basename "$0")"
  echo "Description : git checkout wip"
  echo "----------------------------------"
}

if [[ "$1" == "-h" ]]; then
  usage
  exit 1
fi

if [[ ! -z "$1" ]]; then
  usage
  exit 1
fi

git checkout wip
exit 0
