#!/usr/bin/env bash

usage() {
  echo "----------------------------"
  echo "Usage       : $(basename "$0")"
  echo "Description : launch pcs"
  echo "----------------------------"
  exit 1
}

if [ "$1" == "-h" ] || [ ! -z "$1" ]; then
  usage
fi

code /Users/Shared/pcsetts
exit 0