#!/usr/bin/env bash

usage() {
    echo "----------------------------"
    echo "usage : $(basename "$0") <directory_name>"
    echo "description : procure app"
    echo "----------------------------"
    exit 0
}

utlz="$HOME/zutlz"
cd "$utlz" || exit 1

if [ "$1" == "-h" ] || [ -z "$1" ] || [ ! -d "$utlz/$1" ]; then
    usage
fi

if [ ! -d "${utlz}/$1-prev" ]; then
    mv "$1" "$1-prev"
fi

mkdir "$1"

if [ "$1" = "code" ] && [ ! -d "${utlz}/$1/code-portable-data" ]; then
  mkdir "$1/code-portable-data"
fi

unset utlz
